// tslint:disable
/**
 * JRSAPI
 * JRS Information Management System API
 *
 * The version of the OpenAPI document: v1(Build: 1.0.0.0)
 * Contact: blogic@blogic.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
