//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ServiceModel;
namespace NavDimension
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", ConfigurationName="NavDimension.PMEDimensionValueStaging_Port")]
    public interface PMEDimensionValueStaging_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.Read_Result> ReadAsync(NavDimension.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.ReadByRecId_Result> ReadByRecIdAsync(NavDimension.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.ReadMultiple_Result> ReadMultipleAsync(NavDimension.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.IsUpdated_Result> IsUpdatedAsync(NavDimension.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(NavDimension.GetRecIdFromKey request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione contiene più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.Create_Result> CreateAsync(NavDimension.Create request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione contiene più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.CreateMultiple_Result> CreateMultipleAsync(NavDimension.CreateMultiple request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione contiene più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.Update_Result> UpdateAsync(NavDimension.Update request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione contiene più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavDimension.UpdateMultiple_Result> UpdateMultipleAsync(NavDimension.UpdateMultiple request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging")]
    public partial class PMEDimensionValueStaging
    {
        
        private string keyField;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private string pME_Dimension_CodeField;
        
        private string pME_CodeField;
        
        private string pME_NameField;
        
        private string pME_BlockedField;
        
        private string pME_Global_Dim_NoField;
        
        private string pME_Last_Modified_Date_TimeField;
        
        private string pME_Mapp_Cat_of_IntervField;
        
        private string pME_Cat_of_IntervField;
        
        private string pME_Project_cityField;
        
        private string pME_CompanyField;
        
        private string pME_GuidField;
        
        private bool process_ManuallyField;
        
        private bool process_ManuallyFieldSpecified;
        
        private bool entered_in_NAVField;
        
        private bool entered_in_NAVFieldSpecified;
        
        private bool ignoredField;
        
        private bool ignoredFieldSpecified;
        
        private System.DateTime date_and_time_entered_by_PMEField;
        
        private bool date_and_time_entered_by_PMEFieldSpecified;
        
        private System.DateTime nAV_Processing_date_timeField;
        
        private bool nAV_Processing_date_timeFieldSpecified;
        
        private int version_NoField;
        
        private bool version_NoFieldSpecified;
        
        private bool added_in_MasterField;
        
        private bool added_in_MasterFieldSpecified;
        
        private bool added_in_Slave_CompaniesField;
        
        private bool added_in_Slave_CompaniesFieldSpecified;
        
        private bool is_Blocked_in_Master_CompanyField;
        
        private bool is_Blocked_in_Master_CompanyFieldSpecified;
        
        private bool is_Blocked_in_Slave_CompanyField;
        
        private bool is_Blocked_in_Slave_CompanyFieldSpecified;
        
        private string master_Company_nameField;
        
        private int transaction_ErrorsField;
        
        private bool transaction_ErrorsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Entry_No
        {
            get
            {
                return this.entry_NoField;
            }
            set
            {
                this.entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified
        {
            get
            {
                return this.entry_NoFieldSpecified;
            }
            set
            {
                this.entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PME_Dimension_Code
        {
            get
            {
                return this.pME_Dimension_CodeField;
            }
            set
            {
                this.pME_Dimension_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PME_Code
        {
            get
            {
                return this.pME_CodeField;
            }
            set
            {
                this.pME_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PME_Name
        {
            get
            {
                return this.pME_NameField;
            }
            set
            {
                this.pME_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PME_Blocked
        {
            get
            {
                return this.pME_BlockedField;
            }
            set
            {
                this.pME_BlockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PME_Global_Dim_No
        {
            get
            {
                return this.pME_Global_Dim_NoField;
            }
            set
            {
                this.pME_Global_Dim_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PME_Last_Modified_Date_Time
        {
            get
            {
                return this.pME_Last_Modified_Date_TimeField;
            }
            set
            {
                this.pME_Last_Modified_Date_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PME_Mapp_Cat_of_Interv
        {
            get
            {
                return this.pME_Mapp_Cat_of_IntervField;
            }
            set
            {
                this.pME_Mapp_Cat_of_IntervField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PME_Cat_of_Interv
        {
            get
            {
                return this.pME_Cat_of_IntervField;
            }
            set
            {
                this.pME_Cat_of_IntervField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PME_Project_city
        {
            get
            {
                return this.pME_Project_cityField;
            }
            set
            {
                this.pME_Project_cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PME_Company
        {
            get
            {
                return this.pME_CompanyField;
            }
            set
            {
                this.pME_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PME_Guid
        {
            get
            {
                return this.pME_GuidField;
            }
            set
            {
                this.pME_GuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Process_Manually
        {
            get
            {
                return this.process_ManuallyField;
            }
            set
            {
                this.process_ManuallyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Process_ManuallySpecified
        {
            get
            {
                return this.process_ManuallyFieldSpecified;
            }
            set
            {
                this.process_ManuallyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Entered_in_NAV
        {
            get
            {
                return this.entered_in_NAVField;
            }
            set
            {
                this.entered_in_NAVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entered_in_NAVSpecified
        {
            get
            {
                return this.entered_in_NAVFieldSpecified;
            }
            set
            {
                this.entered_in_NAVFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool Ignored
        {
            get
            {
                return this.ignoredField;
            }
            set
            {
                this.ignoredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IgnoredSpecified
        {
            get
            {
                return this.ignoredFieldSpecified;
            }
            set
            {
                this.ignoredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime Date_and_time_entered_by_PME
        {
            get
            {
                return this.date_and_time_entered_by_PMEField;
            }
            set
            {
                this.date_and_time_entered_by_PMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_and_time_entered_by_PMESpecified
        {
            get
            {
                return this.date_and_time_entered_by_PMEFieldSpecified;
            }
            set
            {
                this.date_and_time_entered_by_PMEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime NAV_Processing_date_time
        {
            get
            {
                return this.nAV_Processing_date_timeField;
            }
            set
            {
                this.nAV_Processing_date_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAV_Processing_date_timeSpecified
        {
            get
            {
                return this.nAV_Processing_date_timeFieldSpecified;
            }
            set
            {
                this.nAV_Processing_date_timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int Version_No
        {
            get
            {
                return this.version_NoField;
            }
            set
            {
                this.version_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Version_NoSpecified
        {
            get
            {
                return this.version_NoFieldSpecified;
            }
            set
            {
                this.version_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool Added_in_Master
        {
            get
            {
                return this.added_in_MasterField;
            }
            set
            {
                this.added_in_MasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Added_in_MasterSpecified
        {
            get
            {
                return this.added_in_MasterFieldSpecified;
            }
            set
            {
                this.added_in_MasterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool Added_in_Slave_Companies
        {
            get
            {
                return this.added_in_Slave_CompaniesField;
            }
            set
            {
                this.added_in_Slave_CompaniesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Added_in_Slave_CompaniesSpecified
        {
            get
            {
                return this.added_in_Slave_CompaniesFieldSpecified;
            }
            set
            {
                this.added_in_Slave_CompaniesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Is_Blocked_in_Master_Company
        {
            get
            {
                return this.is_Blocked_in_Master_CompanyField;
            }
            set
            {
                this.is_Blocked_in_Master_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Is_Blocked_in_Master_CompanySpecified
        {
            get
            {
                return this.is_Blocked_in_Master_CompanyFieldSpecified;
            }
            set
            {
                this.is_Blocked_in_Master_CompanyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool Is_Blocked_in_Slave_Company
        {
            get
            {
                return this.is_Blocked_in_Slave_CompanyField;
            }
            set
            {
                this.is_Blocked_in_Slave_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Is_Blocked_in_Slave_CompanySpecified
        {
            get
            {
                return this.is_Blocked_in_Slave_CompanyFieldSpecified;
            }
            set
            {
                this.is_Blocked_in_Slave_CompanyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Master_Company_name
        {
            get
            {
                return this.master_Company_nameField;
            }
            set
            {
                this.master_Company_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int Transaction_Errors
        {
            get
            {
                return this.transaction_ErrorsField;
            }
            set
            {
                this.transaction_ErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Transaction_ErrorsSpecified
        {
            get
            {
                return this.transaction_ErrorsFieldSpecified;
            }
            set
            {
                this.transaction_ErrorsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging")]
    public partial class PMEDimensionValueStaging_Filter
    {
        
        private PMEDimensionValueStaging_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PMEDimensionValueStaging_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging")]
    public enum PMEDimensionValueStaging_Fields
    {
        
        /// <remarks/>
        Entry_No,
        
        /// <remarks/>
        PME_Dimension_Code,
        
        /// <remarks/>
        PME_Code,
        
        /// <remarks/>
        PME_Name,
        
        /// <remarks/>
        PME_Blocked,
        
        /// <remarks/>
        PME_Global_Dim_No,
        
        /// <remarks/>
        PME_Last_Modified_Date_Time,
        
        /// <remarks/>
        PME_Mapp_Cat_of_Interv,
        
        /// <remarks/>
        PME_Cat_of_Interv,
        
        /// <remarks/>
        PME_Project_city,
        
        /// <remarks/>
        PME_Company,
        
        /// <remarks/>
        PME_Guid,
        
        /// <remarks/>
        Process_Manually,
        
        /// <remarks/>
        Entered_in_NAV,
        
        /// <remarks/>
        Ignored,
        
        /// <remarks/>
        Date_and_time_entered_by_PME,
        
        /// <remarks/>
        NAV_Processing_date_time,
        
        /// <remarks/>
        Version_No,
        
        /// <remarks/>
        Added_in_Master,
        
        /// <remarks/>
        Added_in_Slave_Companies,
        
        /// <remarks/>
        Is_Blocked_in_Master_Company,
        
        /// <remarks/>
        Is_Blocked_in_Slave_Company,
        
        /// <remarks/>
        Master_Company_name,
        
        /// <remarks/>
        Transaction_Errors,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public int Entry_No;
        
        public Read()
        {
        }
        
        public Read(int Entry_No)
        {
            this.Entry_No = Entry_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging;
        
        public Read_Result()
        {
        }
        
        public Read_Result(NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging)
        {
            this.PMEDimensionValueStaging = PMEDimensionValueStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging)
        {
            this.PMEDimensionValueStaging = PMEDimensionValueStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public NavDimension.PMEDimensionValueStaging_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(NavDimension.PMEDimensionValueStaging_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavDimension.PMEDimensionValueStaging[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(NavDimension.PMEDimensionValueStaging[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging;
        
        public Create()
        {
        }
        
        public Create(NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging)
        {
            this.PMEDimensionValueStaging = PMEDimensionValueStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging;
        
        public Create_Result()
        {
        }
        
        public Create_Result(NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging)
        {
            this.PMEDimensionValueStaging = PMEDimensionValueStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List)
        {
            this.PMEDimensionValueStaging_List = PMEDimensionValueStaging_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List)
        {
            this.PMEDimensionValueStaging_List = PMEDimensionValueStaging_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging;
        
        public Update()
        {
        }
        
        public Update(NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging)
        {
            this.PMEDimensionValueStaging = PMEDimensionValueStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        public NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging;
        
        public Update_Result()
        {
        }
        
        public Update_Result(NavDimension.PMEDimensionValueStaging PMEDimensionValueStaging)
        {
            this.PMEDimensionValueStaging = PMEDimensionValueStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List)
        {
            this.PMEDimensionValueStaging_List = PMEDimensionValueStaging_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmedimensionvaluestaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(NavDimension.PMEDimensionValueStaging[] PMEDimensionValueStaging_List)
        {
            this.PMEDimensionValueStaging_List = PMEDimensionValueStaging_List;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface PMEDimensionValueStaging_PortChannel : NavDimension.PMEDimensionValueStaging_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class PMEDimensionValueStaging_PortClient : System.ServiceModel.ClientBase<NavDimension.PMEDimensionValueStaging_Port>, NavDimension.PMEDimensionValueStaging_Port
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
    // Altered following : https://medium.com/grensesnittet/integrating-with-soap-web-services-in-net-core-adebfad173fb

        //public PMEDimensionValueStaging_PortClient() : 
        //        base(PMEDimensionValueStaging_PortClient.GetDefaultBinding(), PMEDimensionValueStaging_PortClient.GetDefaultEndpointAddress())
        //{
        //    this.Endpoint.Name = EndpointConfiguration.PMEDimensionValueStaging_Port.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEDimensionValueStaging_PortClient(EndpointConfiguration endpointConfiguration) : 
        //        base(PMEDimensionValueStaging_PortClient.GetBindingForEndpoint(endpointConfiguration), PMEDimensionValueStaging_PortClient.GetEndpointAddress(endpointConfiguration))
        //{
        //    this.Endpoint.Name = endpointConfiguration.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEDimensionValueStaging_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
        //        base(PMEDimensionValueStaging_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        //{
        //    this.Endpoint.Name = endpointConfiguration.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEDimensionValueStaging_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
        //        base(PMEDimensionValueStaging_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        //{
        //    this.Endpoint.Name = endpointConfiguration.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEDimensionValueStaging_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
        //        base(binding, remoteAddress)
        //{
        //}
        public PMEDimensionValueStaging_PortClient(string endpointUrl, TimeSpan timeout, string username, string password) :
            base(PMEDimensionValueStaging_PortClient.GetBindingForEndpoint(timeout), PMEDimensionValueStaging_PortClient.GetEndpointAddress(endpointUrl))
        {
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
            ConfigureEndpoint(this.Endpoint, clientCredentials: this.ClientCredentials);
       
       }

        
        public PMEDimensionValueStaging_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavDimension.Read_Result> NavDimension.PMEDimensionValueStaging_Port.ReadAsync(NavDimension.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.Read_Result> ReadAsync(int Entry_No)
        {
            NavDimension.Read inValue = new NavDimension.Read();
            inValue.Entry_No = Entry_No;
            return ((NavDimension.PMEDimensionValueStaging_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavDimension.ReadByRecId_Result> NavDimension.PMEDimensionValueStaging_Port.ReadByRecIdAsync(NavDimension.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            NavDimension.ReadByRecId inValue = new NavDimension.ReadByRecId();
            inValue.recId = recId;
            return ((NavDimension.PMEDimensionValueStaging_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavDimension.ReadMultiple_Result> NavDimension.PMEDimensionValueStaging_Port.ReadMultipleAsync(NavDimension.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.ReadMultiple_Result> ReadMultipleAsync(NavDimension.PMEDimensionValueStaging_Filter[] filter, string bookmarkKey, int setSize)
        {
            NavDimension.ReadMultiple inValue = new NavDimension.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((NavDimension.PMEDimensionValueStaging_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavDimension.IsUpdated_Result> NavDimension.PMEDimensionValueStaging_Port.IsUpdatedAsync(NavDimension.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            NavDimension.IsUpdated inValue = new NavDimension.IsUpdated();
            inValue.Key = Key;
            return ((NavDimension.PMEDimensionValueStaging_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavDimension.GetRecIdFromKey_Result> NavDimension.PMEDimensionValueStaging_Port.GetRecIdFromKeyAsync(NavDimension.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            NavDimension.GetRecIdFromKey inValue = new NavDimension.GetRecIdFromKey();
            inValue.Key = Key;
            return ((NavDimension.PMEDimensionValueStaging_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<NavDimension.Create_Result> CreateAsync(NavDimension.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.CreateMultiple_Result> CreateMultipleAsync(NavDimension.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.Update_Result> UpdateAsync(NavDimension.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavDimension.UpdateMultiple_Result> UpdateMultipleAsync(NavDimension.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
  // Altered following : https://medium.com/grensesnittet/integrating-with-soap-web-services-in-net-core-adebfad173fb

        //private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        //{
        //    if ((endpointConfiguration == EndpointConfiguration.PMEDimensionValueStaging_Port))
        //    {
        //        System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
        //        result.MaxBufferSize = int.MaxValue;
        //        result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
        //        result.MaxReceivedMessageSize = int.MaxValue;
        //        result.AllowCookies = true;
        //        result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
        //        return result;
        //    }
        //    throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        //}

        //private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        //{
        //    if ((endpointConfiguration == EndpointConfiguration.PMEDimensionValueStaging_Port))
        //    {
        //        return new System.ServiceModel.EndpointAddress("https://navstaging.jrs.net:7047/jrsnavtest/WS/MASTER COMPANY_/Page/DimValueStagin" +
        //                "g");
        //    }
        //    throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        //}

        //private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        //{
        //    return PMEDimensionValueStaging_PortClient.GetBindingForEndpoint(EndpointConfiguration.PMEDimensionValueStaging_Port);
        //}

        //private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        //{
        //    return PMEDimensionValueStaging_PortClient.GetEndpointAddress(EndpointConfiguration.PMEDimensionValueStaging_Port);
        //}

        //public enum EndpointConfiguration
        //{

        //    PMEDimensionValueStaging_Port,
        //}
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(TimeSpan timeout)
        {
            var httpsBinding = new BasicHttpsBinding();
            httpsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
            httpsBinding.Security.Mode = BasicHttpsSecurityMode.Transport;

            var integerMaxValue = int.MaxValue;
            httpsBinding.MaxBufferSize = integerMaxValue;
            httpsBinding.MaxReceivedMessageSize = integerMaxValue;
            httpsBinding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            httpsBinding.AllowCookies = true;

            httpsBinding.ReceiveTimeout = timeout;
            httpsBinding.SendTimeout = timeout;
            httpsBinding.OpenTimeout = timeout;
            httpsBinding.CloseTimeout = timeout;

            return httpsBinding;
        }
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(string endpointUrl)
        {
            if (!endpointUrl.StartsWith("https://"))
            {
                throw new UriFormatException("The endpoint URL must start with https://.");
            }
            return new System.ServiceModel.EndpointAddress(endpointUrl);
        }
    }
}