CREATE TABLE [dbo].[HR_AGREEMENT] (
    [HR_AGREEMENT_ID]          INT              IDENTITY (1, 1) NOT NULL,
    [IMS_USER_UID]             UNIQUEIDENTIFIER NOT NULL,
    [HR_EMPLOYEMENT_DATE_FROM] DATE             NOT NULL,
    [HR_EMPLOYEMENT_DATE_TO]   DATE             NULL,
    [HR_WORK_HOURS]            VARCHAR (50)     NULL,
    CONSTRAINT [PK_HR_AGREEMENT] PRIMARY KEY CLUSTERED ([HR_AGREEMENT_ID] ASC)
);

