CREATE TABLE [dbo].[HR_AGREEMENT_TYPE] (
    [HR_AGREEMENT_TYPE_ID]    INT            IDENTITY (1, 1) NOT NULL,
    [HR_AGREEMENT_TYPE_NAME]  VARCHAR (50)   NOT NULL,
    [HR_AGREEMENT_TYPE_DESCR] NVARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([HR_AGREEMENT_TYPE_ID] ASC)
);

