CREATE TABLE [dbo].[HR_DOCUMENT] (
    [HR_DOCUMENT_ID]          INT          IDENTITY (1, 1) NOT NULL,
    [HR_BIODATA_ID]           INT          NOT NULL,
    [HR_DOCUMENT_TYPE_ID]     INT          NOT NULL,
    [HR_DOCUMENT_NUMBER]      VARCHAR (50) NULL,
    [HR_DOCUMENT_EXPIRY_DATE] DATE         NOT NULL,
    PRIMARY KEY CLUSTERED ([HR_DOCUMENT_ID] ASC),
    FOREIGN KEY ([HR_DOCUMENT_TYPE_ID]) REFERENCES [dbo].[HR_DOCUMENT_TYPE] ([HR_DOCUMENT_TYPE_ID]),
    CONSTRAINT [FK__HR_DOCUME__HR_BI__2B0A656D] FOREIGN KEY ([HR_BIODATA_ID]) REFERENCES [dbo].[HR_BIODATA] ([HR_BIODATA_ID])
);

