CREATE TABLE [dbo].[HR_DEPARTMENT] (
    [HR_DEPARTMENT_ID]    INT             IDENTITY (1, 1) NOT NULL,
    [HR_DEPARTMENT_DESCR] NVARCHAR (2500) NOT NULL,
    PRIMARY KEY CLUSTERED ([HR_DEPARTMENT_ID] ASC)
);

