CREATE TABLE [dbo].[HR_DOCUMENT_TYPE] (
    [HR_DOCUMENT_TYPE_ID]    INT          IDENTITY (1, 1) NOT NULL,
    [HR_DOCUMENT_TYPE_DESCR] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([HR_DOCUMENT_TYPE_ID] ASC)
);

