CREATE TABLE [dbo].[HR_POSITION] (
    [HR_POSITION_ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [HR_POSITION_STATUS_ID]            INT            NULL,
    [HR_POSITION_SCOPE_ID]             INT            NOT NULL,
    [HR_POSITION_FUNCTION_ID]          INT            NOT NULL,
    [HR_POSITION_LEVEL_ID]             INT            NOT NULL,
    [HR_POSITION_DEPARTMENT_ID]        INT            NOT NULL,
    [HR_POSITION_DESCR]                NVARCHAR (MAX) NOT NULL,
    [HR_POSITION_SUPERIOR_POSITION_ID] INT            NULL,
    [HR_POSITION_SKILLS]               NVARCHAR (MAX) NULL,
    [HR_POSITION_PROJECT_ID]           INT            NOT NULL,
    [HR_POSITION_AGREEMENT_ID]         INT            NULL,
    [HR_POSITION_AGREEMENT_TYPE_ID]    INT            NULL,
    [HR_POSITION_LOCATION_ID]          INT            NULL,
    PRIMARY KEY CLUSTERED ([HR_POSITION_ID] ASC),
    FOREIGN KEY ([HR_POSITION_DEPARTMENT_ID]) REFERENCES [dbo].[HR_DEPARTMENT] ([HR_DEPARTMENT_ID]),
    FOREIGN KEY ([HR_POSITION_FUNCTION_ID]) REFERENCES [dbo].[HR_TITLE_FUNCTION] ([HR_TITLE_FUNCTION_ID]),
    FOREIGN KEY ([HR_POSITION_LEVEL_ID]) REFERENCES [dbo].[HR_TITLE_LEVEL] ([HR_TITLE_LEVEL_ID]),
    FOREIGN KEY ([HR_POSITION_LOCATION_ID]) REFERENCES [dbo].[IMS_LOCATION] ([IMS_LOCATION_ID]),
    FOREIGN KEY ([HR_POSITION_PROJECT_ID]) REFERENCES [dbo].[IMS_PROJECT] ([IMS_PROJECT_ID]),
    FOREIGN KEY ([HR_POSITION_SCOPE_ID]) REFERENCES [dbo].[HR_TITLE_SCOPE] ([HR_TITLE_SCOPE_ID]),
    FOREIGN KEY ([HR_POSITION_SUPERIOR_POSITION_ID]) REFERENCES [dbo].[HR_POSITION] ([HR_POSITION_ID]),
    CONSTRAINT [FK_HR_POSITION_HR_AGREEMENT] FOREIGN KEY ([HR_POSITION_AGREEMENT_ID]) REFERENCES [dbo].[HR_AGREEMENT] ([HR_AGREEMENT_ID]),
    CONSTRAINT [FK_HR_POSITION_HR_AGREEMENT_TYPE] FOREIGN KEY ([HR_POSITION_AGREEMENT_TYPE_ID]) REFERENCES [dbo].[HR_AGREEMENT_TYPE] ([HR_AGREEMENT_TYPE_ID])
);









