CREATE TABLE [dbo].[HR_PERSONAL_TITLE] (
    [HR_PERSONAL_TITLE_ID]    INT          IDENTITY (1, 1) NOT NULL,
    [HR_PERSONAL_TITLE_DESCR] VARCHAR (10) NOT NULL,
    PRIMARY KEY CLUSTERED ([HR_PERSONAL_TITLE_ID] ASC)
);

