CREATE TABLE [dbo].[HR_TITLE_FUNCTION] (
    [HR_TITLE_FUNCTION_ID]    INT             IDENTITY (1, 1) NOT NULL,
    [HR_TITLE_FUNCTION_DESCR] NVARCHAR (2500) NOT NULL,
    PRIMARY KEY CLUSTERED ([HR_TITLE_FUNCTION_ID] ASC)
);

