CREATE TABLE [dbo].[IMS_ROLE_MENU] (
    [IMS_ROLE_MENU_ID]           INT IDENTITY (1, 1) NOT NULL,
    [IMS_ROLE_MENU_USER_ROLE_ID] INT NOT NULL,
    [IMS_ROLE_MENU_MENU_ID]      INT NOT NULL,
    PRIMARY KEY CLUSTERED ([IMS_ROLE_MENU_ID] ASC),
    FOREIGN KEY ([IMS_ROLE_MENU_MENU_ID]) REFERENCES [dbo].[MENU] ([ID]),
    FOREIGN KEY ([IMS_ROLE_MENU_USER_ROLE_ID]) REFERENCES [dbo].[IMS_USER_ROLE] ([IMS_USER_ROLE_ID])
);

