CREATE TABLE [dbo].[IMS_LOOKUP_TYPE] (
    [IMS_LOOKUP_TYPE_ID]    INT            IDENTITY (1, 1) NOT NULL,
    [IMS_LOOKUP_TYPE_CODE]  NVARCHAR (25)  NOT NULL,
    [IMS_LOOKUP_TYPE_DESCR] NVARCHAR (250) NOT NULL,
    PRIMARY KEY CLUSTERED ([IMS_LOOKUP_TYPE_ID] ASC)
);

