CREATE TABLE [dbo].[IMS_NARRATIVE_SECTION_TYPE] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [CODE]       VARCHAR (25)  NOT NULL,
    [TABLE_NAME] VARCHAR (128) NOT NULL,
    [DESCR]      VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

