CREATE TABLE [dbo].[IMS_NARRATIVE_INFO] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [REFERENCE_TABLE_NAME] VARCHAR (128)  NOT NULL,
    [REFERENCE_ID]         INT            NOT NULL,
    [NARRATIVE_CODE]       VARCHAR (25)   NULL,
    [NARRATIVE_TITLE]      VARCHAR (250)  NULL,
    [NARRATIVE_VALUE]      NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([NARRATIVE_CODE] ASC)
);

