CREATE TABLE [dbo].[IMS_USER_RIGHTS] (
    [IMS_USER_RIGHTS_ID]           INT              IDENTITY (1, 1) NOT NULL,
    [IMS_USER_RIGHTS_USER_UID]     UNIQUEIDENTIFIER NOT NULL,
    [IMS_USER_RIGHTS_USER_ROLE_ID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([IMS_USER_RIGHTS_ID] ASC),
    FOREIGN KEY ([IMS_USER_RIGHTS_USER_ROLE_ID]) REFERENCES [dbo].[IMS_USER_ROLE] ([IMS_USER_ROLE_ID]),
    FOREIGN KEY ([IMS_USER_RIGHTS_USER_UID]) REFERENCES [dbo].[IMS_USER] ([IMS_USER_UID])
);

