CREATE TABLE [dbo].[IMS_TABLE_CRUD_DETAILS] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [TABLE_NAME]     VARCHAR (128) NULL,
    [CREATE_SP_NAME] VARCHAR (128) NULL,
    [READ_SP_NAME]   VARCHAR (128) DEFAULT ('dbo.UTIL_SP_GENERIC_QUERY_DATA') NULL,
    [UPDATE_SP_NAME] VARCHAR (128) NULL,
    [DELETE_SP_NAME] VARCHAR (128) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

