CREATE TABLE [dbo].[IMS_LOCATION] (
    [IMS_LOCATION_ID]               INT             IDENTITY (1, 1) NOT NULL,
    [IMS_LOCATION_ADMIN_AREA_ID_1]  INT             NOT NULL,
    [IMS_LOCATION_ADMIN_AREA_ID_2]  INT             NOT NULL,
    [IMS_LOCATION_ADMIN_AREA_ID_3]  INT             NOT NULL,
    [IMS_LOCATION_ADDRESS]          VARCHAR (250)   NULL,
    [IMS_LOCATION_HISTORIC_ADDRESS] NVARCHAR (1000) NULL,
    [IMS_LOCATION_LAT]              DECIMAL (9, 6)  NULL,
    [IMS_LOCATION_LON]              DECIMAL (9, 6)  NULL,
    [IMS_LOCATION_CODE]             VARCHAR (15)    NULL,
    PRIMARY KEY CLUSTERED ([IMS_LOCATION_ID] ASC),
    FOREIGN KEY ([IMS_LOCATION_ADMIN_AREA_ID_1]) REFERENCES [dbo].[IMS_ADMIN_AREA] ([IMS_ADMIN_AREA_ID]),
    FOREIGN KEY ([IMS_LOCATION_ADMIN_AREA_ID_2]) REFERENCES [dbo].[IMS_ADMIN_AREA] ([IMS_ADMIN_AREA_ID]),
    FOREIGN KEY ([IMS_LOCATION_ADMIN_AREA_ID_3]) REFERENCES [dbo].[IMS_ADMIN_AREA] ([IMS_ADMIN_AREA_ID])
);





