CREATE TABLE [dbo].[IMS_LANGUAGE] (
    [IMS_LANGUAGE_ID]             INT             IDENTITY (1, 1) NOT NULL,
    [IMS_LANGUAGE_ISO_639_1_CODE] VARCHAR (5)     NOT NULL,
    [IMS_LANGUAGE_NAME]           NVARCHAR (500)  NOT NULL,
    [IMS_LANGUAGE_FAMILY]         NVARCHAR (500)  NULL,
    [IMS_LNAGUAGE_NOTES]          NVARCHAR (2000) NULL,
    [IMS_LANGUAGE_LOCALE]         VARCHAR (5)     NULL,
    PRIMARY KEY CLUSTERED ([IMS_LANGUAGE_ID] ASC)
);

