CREATE TABLE [dbo].[IMS_ADMIN_AREA_TYPE] (
    [IMS_ADMIN_AREA_TYPE_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [IMS_ADMIN_AREA_TYPE_CODE]  VARCHAR (10)  NOT NULL,
    [IMS_ADMIN_AREA_TYPE_NAME]  VARCHAR (25)  NOT NULL,
    [IMS_ADMIN_AREA_TYPE_DESCR] VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([IMS_ADMIN_AREA_TYPE_ID] ASC)
);

