CREATE TABLE [dbo].[IMS_STATUS_CLASS] (
    [IMS_STATUS_CLASS_ID]          INT            IDENTITY (1, 1) NOT NULL,
    [IMS_STATUS_CLASS_DESCR]       VARCHAR (2500) NOT NULL,
    [IMS_STATUS_CLASS_OBJECT_NAME] VARCHAR (2500) NOT NULL,
    PRIMARY KEY CLUSTERED ([IMS_STATUS_CLASS_ID] ASC)
);

