CREATE TABLE [dbo].[IMS_FORM_FIELD_TYPE] (
    [ID]    INT           IDENTITY (1, 1) NOT NULL,
    [CODE]  VARCHAR (50)  NOT NULL,
    [DESCR] VARCHAR (250) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([CODE] ASC),
    UNIQUE NONCLUSTERED ([DESCR] ASC)
);

