CREATE TABLE [dbo].[IMS_STATUS] (
    [IMS_STATUS_ID]              INT             IDENTITY (1, 1) NOT NULL,
    [IMS_STATUS_STATUS_CLASS_ID] INT             NOT NULL,
    [IMS_STATUS_NAME]            VARCHAR (250)   NOT NULL,
    [IMS_STATUS_DESCR]           NVARCHAR (3000) NOT NULL,
    PRIMARY KEY CLUSTERED ([IMS_STATUS_ID] ASC),
    FOREIGN KEY ([IMS_STATUS_STATUS_CLASS_ID]) REFERENCES [dbo].[IMS_STATUS_CLASS] ([IMS_STATUS_CLASS_ID])
);

