CREATE TABLE [dbo].[PMS_CATEGORY_OF_INTERVENTION] (
    [PMS_COI_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [PMS_COI_CODE]        VARCHAR (50)  NULL,
    [PMS_COI_DESCRIPTION] VARCHAR (MAX) NULL,
    [PMS_COI_ENABLED]     BIT           NOT NULL,
    [PMS_COI_DELETED]     BIT           CONSTRAINT [DF_PMS_CATEGORY_OF_INTERVENTION_PMS_COI_DELETED] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PMS_CATEGORY_OF_INTERVENTION] PRIMARY KEY CLUSTERED ([PMS_COI_ID] ASC)
);

