CREATE TABLE [dbo].[TEST_DEPARTMENT] (
    [TEST_DEPARTMENT_ID]    INT             IDENTITY (1, 1) NOT NULL,
    [TEST_DEPARTMENT_DESCR] NVARCHAR (2500) NOT NULL,
    PRIMARY KEY CLUSTERED ([TEST_DEPARTMENT_ID] ASC)
);

