//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ServiceModel;

namespace NavGLBudget
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", ConfigurationName="NavGLBudget.PMEGLBudgetEntryStaging_Port")]
    public interface PMEGLBudgetEntryStaging_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavGLBudget.Read_Result> ReadAsync(NavGLBudget.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavGLBudget.ReadByRecId_Result> ReadByRecIdAsync(NavGLBudget.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavGLBudget.ReadMultiple_Result> ReadMultipleAsync(NavGLBudget.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavGLBudget.IsUpdated_Result> IsUpdatedAsync(NavGLBudget.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavGLBudget.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(NavGLBudget.GetRecIdFromKey request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione contiene più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavGLBudget.Create_Result> CreateAsync(NavGLBudget.Create request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione contiene più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavGLBudget.CreateMultiple_Result> CreateMultipleAsync(NavGLBudget.CreateMultiple request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging")]
    public partial class PMEGLBudgetEntryStaging
    {
        
        private string keyField;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private string pME_Budget_NameField;
        
        private string pME_G_L_Account_NoField;
        
        private string pME_DateField;
        
        private string pME_Global_Dimension_1_CodeField;
        
        private string pME_Global_Dimension_2_CodeField;
        
        private string pME_AmountField;
        
        private string pME_DescriptionField;
        
        private string pME_Budget_Dimension_1_CodeField;
        
        private string pME_Budget_Dimension_2_CodeField;
        
        private string pME_Budget_Dimension_3_CodeField;
        
        private string pME_Budget_Dimension_4_CodeField;
        
        private string pME_Budget_Dimension_5_CodeField;
        
        private string pME_Budget_Dimension_6_CodeField;
        
        private string pME_Budget_Dimension_7_CodeField;
        
        private string pME_Budget_Dimension_8_CodeField;
        
        private string pME_Budget_Dimension_9_CodeField;
        
        private string pME_Budget_Dimension_10_CodeField;
        
        private string pME_Budget_Dimension_11_CodeField;
        
        private string pME_Budget_Dimension_12_CodeField;
        
        private string pME_Budget_Dimension_13_CodeField;
        
        private string pME_Budget_Dimension_14_CodeField;
        
        private string pME_Unit_of_Measure_CodeField;
        
        private string pME_QuantityField;
        
        private string pME_Unit_Cost_LCYField;
        
        private string pME_Entry_NoField;
        
        private string pME_Last_Date_ModifiedField;
        
        private string pME_DeletedField;
        
        private string pME_CompanyField;
        
        private bool process_manuallyField;
        
        private bool process_manuallyFieldSpecified;
        
        private bool entered_in_NAVField;
        
        private bool entered_in_NAVFieldSpecified;
       
        private bool ignoredField;
        
        private bool ignoredFieldSpecified;
        
        private System.DateTime date_and_time_entered_by_PMEField;
        
        private bool date_and_time_entered_by_PMEFieldSpecified;
        
        private System.DateTime nAV_Processing_date_timeField;
        
        private bool nAV_Processing_date_timeFieldSpecified;
        
        private int version_NoField;
        
        private bool version_NoFieldSpecified;
        
        private bool processed_in_Slave_CompanyField;
        
        private bool processed_in_Slave_CompanyFieldSpecified;
        
        private int transaction_ErrorsField;
        
        private bool transaction_ErrorsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Entry_No
        {
            get
            {
                return this.entry_NoField;
            }
            set
            {
                this.entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified
        {
            get
            {
                return this.entry_NoFieldSpecified;
            }
            set
            {
                this.entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PME_Budget_Name
        {
            get
            {
                return this.pME_Budget_NameField;
            }
            set
            {
                this.pME_Budget_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PME_G_L_Account_No
        {
            get
            {
                return this.pME_G_L_Account_NoField;
            }
            set
            {
                this.pME_G_L_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PME_Date
        {
            get
            {
                return this.pME_DateField;
            }
            set
            {
                this.pME_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PME_Global_Dimension_1_Code
        {
            get
            {
                return this.pME_Global_Dimension_1_CodeField;
            }
            set
            {
                this.pME_Global_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PME_Global_Dimension_2_Code
        {
            get
            {
                return this.pME_Global_Dimension_2_CodeField;
            }
            set
            {
                this.pME_Global_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PME_Amount
        {
            get
            {
                return this.pME_AmountField;
            }
            set
            {
                this.pME_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PME_Description
        {
            get
            {
                return this.pME_DescriptionField;
            }
            set
            {
                this.pME_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PME_Budget_Dimension_1_Code
        {
            get
            {
                return this.pME_Budget_Dimension_1_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PME_Budget_Dimension_2_Code
        {
            get
            {
                return this.pME_Budget_Dimension_2_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PME_Budget_Dimension_3_Code
        {
            get
            {
                return this.pME_Budget_Dimension_3_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_3_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PME_Budget_Dimension_4_Code
        {
            get
            {
                return this.pME_Budget_Dimension_4_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_4_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PME_Budget_Dimension_5_Code
        {
            get
            {
                return this.pME_Budget_Dimension_5_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_5_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PME_Budget_Dimension_6_Code
        {
            get
            {
                return this.pME_Budget_Dimension_6_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_6_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PME_Budget_Dimension_7_Code
        {
            get
            {
                return this.pME_Budget_Dimension_7_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_7_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PME_Budget_Dimension_8_Code
        {
            get
            {
                return this.pME_Budget_Dimension_8_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_8_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PME_Budget_Dimension_9_Code
        {
            get
            {
                return this.pME_Budget_Dimension_9_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_9_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PME_Budget_Dimension_10_Code
        {
            get
            {
                return this.pME_Budget_Dimension_10_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_10_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string PME_Budget_Dimension_11_Code
        {
            get
            {
                return this.pME_Budget_Dimension_11_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_11_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PME_Budget_Dimension_12_Code
        {
            get
            {
                return this.pME_Budget_Dimension_12_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_12_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string PME_Budget_Dimension_13_Code
        {
            get
            {
                return this.pME_Budget_Dimension_13_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_13_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PME_Budget_Dimension_14_Code
        {
            get
            {
                return this.pME_Budget_Dimension_14_CodeField;
            }
            set
            {
                this.pME_Budget_Dimension_14_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string PME_Unit_of_Measure_Code
        {
            get
            {
                return this.pME_Unit_of_Measure_CodeField;
            }
            set
            {
                this.pME_Unit_of_Measure_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string PME_Quantity
        {
            get
            {
                return this.pME_QuantityField;
            }
            set
            {
                this.pME_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PME_Unit_Cost_LCY
        {
            get
            {
                return this.pME_Unit_Cost_LCYField;
            }
            set
            {
                this.pME_Unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string PME_Entry_No
        {
            get
            {
                return this.pME_Entry_NoField;
            }
            set
            {
                this.pME_Entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string PME_Last_Date_Modified
        {
            get
            {
                return this.pME_Last_Date_ModifiedField;
            }
            set
            {
                this.pME_Last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string PME_Deleted
        {
            get
            {
                return this.pME_DeletedField;
            }
            set
            {
                this.pME_DeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string PME_Company
        {
            get
            {
                return this.pME_CompanyField;
            }
            set
            {
                this.pME_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool Process_manually
        {
            get
            {
                return this.process_manuallyField;
            }
            set
            {
                this.process_manuallyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Process_manuallySpecified
        {
            get
            {
                return this.process_manuallyFieldSpecified;
            }
            set
            {
                this.process_manuallyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool Entered_in_NAV
        {
            get
            {
                return this.entered_in_NAVField;
            }
            set
            {
                this.entered_in_NAVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entered_in_NAVSpecified
        {
            get
            {
                return this.entered_in_NAVFieldSpecified;
            }
            set
            {
                this.entered_in_NAVFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public bool Ignored
        {
            get
            {
                return this.ignoredField;
            }
            set
            {
                this.ignoredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IgnoredSpecified
        {
            get
            {
                return this.ignoredFieldSpecified;
            }
            set
            {
                this.ignoredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public System.DateTime date_and_time_entered_by_PME
        {
            get
            {
                return this.date_and_time_entered_by_PMEField;
            }
            set
            {
                this.date_and_time_entered_by_PMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool date_and_time_entered_by_PMESpecified
        {
            get
            {
                return this.date_and_time_entered_by_PMEFieldSpecified;
            }
            set
            {
                this.date_and_time_entered_by_PMEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public System.DateTime NAV_Processing_date_time
        {
            get
            {
                return this.nAV_Processing_date_timeField;
            }
            set
            {
                this.nAV_Processing_date_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAV_Processing_date_timeSpecified
        {
            get
            {
                return this.nAV_Processing_date_timeFieldSpecified;
            }
            set
            {
                this.nAV_Processing_date_timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int Version_No
        {
            get
            {
                return this.version_NoField;
            }
            set
            {
                this.version_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Version_NoSpecified
        {
            get
            {
                return this.version_NoFieldSpecified;
            }
            set
            {
                this.version_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public bool Processed_in_Slave_Company
        {
            get
            {
                return this.processed_in_Slave_CompanyField;
            }
            set
            {
                this.processed_in_Slave_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Processed_in_Slave_CompanySpecified
        {
            get
            {
                return this.processed_in_Slave_CompanyFieldSpecified;
            }
            set
            {
                this.processed_in_Slave_CompanyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int Transaction_Errors
        {
            get
            {
                return this.transaction_ErrorsField;
            }
            set
            {
                this.transaction_ErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Transaction_ErrorsSpecified
        {
            get
            {
                return this.transaction_ErrorsFieldSpecified;
            }
            set
            {
                this.transaction_ErrorsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging")]
    public partial class PMEGLBudgetEntryStaging_Filter
    {
        
        private PMEGLBudgetEntryStaging_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PMEGLBudgetEntryStaging_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging")]
    public enum PMEGLBudgetEntryStaging_Fields
    {
        
        /// <remarks/>
        Entry_No,
        
        /// <remarks/>
        PME_Budget_Name,
        
        /// <remarks/>
        PME_G_L_Account_No,
        
        /// <remarks/>
        PME_Date,
        
        /// <remarks/>
        PME_Global_Dimension_1_Code,
        
        /// <remarks/>
        PME_Global_Dimension_2_Code,
        
        /// <remarks/>
        PME_Amount,
        
        /// <remarks/>
        PME_Description,
        
        /// <remarks/>
        PME_Budget_Dimension_1_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_2_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_3_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_4_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_5_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_6_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_7_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_8_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_9_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_10_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_11_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_12_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_13_Code,
        
        /// <remarks/>
        PME_Budget_Dimension_14_Code,
        
        /// <remarks/>
        PME_Unit_of_Measure_Code,
        
        /// <remarks/>
        PME_Quantity,
        
        /// <remarks/>
        PME_Unit_Cost_LCY,
        
        /// <remarks/>
        PME_Entry_No,
        
        /// <remarks/>
        PME_Last_Date_Modified,
        
        /// <remarks/>
        PME_Deleted,
        
        /// <remarks/>
        PME_Company,
        
        /// <remarks/>
        Process_manually,
        
        /// <remarks/>
        Entered_in_NAV,
        
        /// <remarks/>
        Ignored,
        
        /// <remarks/>
        date_and_time_entered_by_PME,
        
        /// <remarks/>
        NAV_Processing_date_time,
        
        /// <remarks/>
        Version_No,
        
        /// <remarks/>
        Processed_in_Slave_Company,
        
        /// <remarks/>
        Transaction_Errors,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public int Entry_No;
        
        public Read()
        {
        }
        
        public Read(int Entry_No)
        {
            this.Entry_No = Entry_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging;
        
        public Read_Result()
        {
        }
        
        public Read_Result(NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging)
        {
            this.PMEGLBudgetEntryStaging = PMEGLBudgetEntryStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging)
        {
            this.PMEGLBudgetEntryStaging = PMEGLBudgetEntryStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public NavGLBudget.PMEGLBudgetEntryStaging_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(NavGLBudget.PMEGLBudgetEntryStaging_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavGLBudget.PMEGLBudgetEntryStaging[]  ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(NavGLBudget.PMEGLBudgetEntryStaging[]  ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging;
        
        public Create()
        {
        }
        
        public Create(NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging)
        {
            this.PMEGLBudgetEntryStaging = PMEGLBudgetEntryStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging;
        
        public Create_Result()
        {
        }
        
        public Create_Result(NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging)
        {
            this.PMEGLBudgetEntryStaging = PMEGLBudgetEntryStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List)
        {
            this.PMEGLBudgetEntryStaging_List = PMEGLBudgetEntryStaging_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List)
        {
            this.PMEGLBudgetEntryStaging_List = PMEGLBudgetEntryStaging_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging;
        
        public Update()
        {
        }
        
        public Update(NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging)
        {
            this.PMEGLBudgetEntryStaging = PMEGLBudgetEntryStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        public NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging;
        
        public Update_Result()
        {
        }
        
        public Update_Result(NavGLBudget.PMEGLBudgetEntryStaging PMEGLBudgetEntryStaging)
        {
            this.PMEGLBudgetEntryStaging = PMEGLBudgetEntryStaging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List)
        {
            this.PMEGLBudgetEntryStaging_List = PMEGLBudgetEntryStaging_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pmeglbudgetentrystaging", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(NavGLBudget.PMEGLBudgetEntryStaging[]  PMEGLBudgetEntryStaging_List)
        {
            this.PMEGLBudgetEntryStaging_List = PMEGLBudgetEntryStaging_List;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface PMEGLBudgetEntryStaging_PortChannel : NavGLBudget.PMEGLBudgetEntryStaging_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class PMEGLBudgetEntryStaging_PortClient : System.ServiceModel.ClientBase<NavGLBudget.PMEGLBudgetEntryStaging_Port>, NavGLBudget.PMEGLBudgetEntryStaging_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        // Altered following : https://medium.com/grensesnittet/integrating-with-soap-web-services-in-net-core-adebfad173fb

        //public PMEGLBudgetEntryStaging_PortClient() : 
        //        base(PMEGLBudgetEntryStaging_PortClient.GetDefaultBinding(), PMEGLBudgetEntryStaging_PortClient.GetDefaultEndpointAddress())
        //{
        //    this.Endpoint.Name = EndpointConfiguration.PMEGLBudgetEntryStaging_Port.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEGLBudgetEntryStaging_PortClient(EndpointConfiguration endpointConfiguration) : 
        //        base(PMEGLBudgetEntryStaging_PortClient.GetBindingForEndpoint(endpointConfiguration), PMEGLBudgetEntryStaging_PortClient.GetEndpointAddress(endpointConfiguration))
        //{
        //    this.Endpoint.Name = endpointConfiguration.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEGLBudgetEntryStaging_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
        //        base(PMEGLBudgetEntryStaging_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        //{
        //    this.Endpoint.Name = endpointConfiguration.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEGLBudgetEntryStaging_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
        //        base(PMEGLBudgetEntryStaging_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        //{
        //    this.Endpoint.Name = endpointConfiguration.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}

        //public PMEGLBudgetEntryStaging_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
        //        base(binding, remoteAddress)
        //{
        //}
        public PMEGLBudgetEntryStaging_PortClient(string endpointUrl, TimeSpan timeout, string username, string password) :
            base(PMEGLBudgetEntryStaging_PortClient.GetBindingForEndpoint(timeout), PMEGLBudgetEntryStaging_PortClient.GetEndpointAddress(endpointUrl))
        {
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PMEGLBudgetEntryStaging_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
         base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavGLBudget.Read_Result> NavGLBudget.PMEGLBudgetEntryStaging_Port.ReadAsync(NavGLBudget.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavGLBudget.Read_Result> ReadAsync(int Entry_No)
        {
            NavGLBudget.Read inValue = new NavGLBudget.Read();
            inValue.Entry_No = Entry_No;
            return ((NavGLBudget.PMEGLBudgetEntryStaging_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavGLBudget.ReadByRecId_Result> NavGLBudget.PMEGLBudgetEntryStaging_Port.ReadByRecIdAsync(NavGLBudget.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavGLBudget.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            NavGLBudget.ReadByRecId inValue = new NavGLBudget.ReadByRecId();
            inValue.recId = recId;
            return ((NavGLBudget.PMEGLBudgetEntryStaging_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavGLBudget.ReadMultiple_Result> NavGLBudget.PMEGLBudgetEntryStaging_Port.ReadMultipleAsync(NavGLBudget.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavGLBudget.ReadMultiple_Result> ReadMultipleAsync(NavGLBudget.PMEGLBudgetEntryStaging_Filter[] filter, string bookmarkKey, int setSize)
        {
            NavGLBudget.ReadMultiple inValue = new NavGLBudget.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((NavGLBudget.PMEGLBudgetEntryStaging_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavGLBudget.IsUpdated_Result> NavGLBudget.PMEGLBudgetEntryStaging_Port.IsUpdatedAsync(NavGLBudget.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavGLBudget.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            NavGLBudget.IsUpdated inValue = new NavGLBudget.IsUpdated();
            inValue.Key = Key;
            return ((NavGLBudget.PMEGLBudgetEntryStaging_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavGLBudget.GetRecIdFromKey_Result> NavGLBudget.PMEGLBudgetEntryStaging_Port.GetRecIdFromKeyAsync(NavGLBudget.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavGLBudget.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            NavGLBudget.GetRecIdFromKey inValue = new NavGLBudget.GetRecIdFromKey();
            inValue.Key = Key;
            return ((NavGLBudget.PMEGLBudgetEntryStaging_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<NavGLBudget.Create_Result> CreateAsync(NavGLBudget.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavGLBudget.CreateMultiple_Result> CreateMultipleAsync(NavGLBudget.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }


        // Altered following : https://medium.com/grensesnittet/integrating-with-soap-web-services-in-net-core-adebfad173fb
        //private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        //{
        //    if ((endpointConfiguration == EndpointConfiguration.PMEGLBudgetEntryStaging_Port))
        //    {
        //        System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
        //        result.MaxBufferSize = int.MaxValue;
        //        result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
        //        result.MaxReceivedMessageSize = int.MaxValue;
        //        result.AllowCookies = true;
        //        result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
        //        return result;
        //    }
        //    throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        //}

        //private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        //{
        //    if ((endpointConfiguration == EndpointConfiguration.PMEGLBudgetEntryStaging_Port))
        //    {
        //        return new System.ServiceModel.EndpointAddress("https://navstaging.jrs.net:7047/jrsnavtest/WS/MASTER COMPANY_/Page/GLBudgetEntryS" +
        //                "taging");
        //    }
        //    throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        //}

        //private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        //{
        //    return PMEGLBudgetEntryStaging_PortClient.GetBindingForEndpoint(EndpointConfiguration.PMEGLBudgetEntryStaging_Port);
        //}

        //private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        //{
        //    return PMEGLBudgetEntryStaging_PortClient.GetEndpointAddress(EndpointConfiguration.PMEGLBudgetEntryStaging_Port);
        //}

        //public enum EndpointConfiguration
        //{

        //    PMEGLBudgetEntryStaging_Port,
        //}
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(TimeSpan timeout)
        {
            var httpsBinding = new BasicHttpsBinding();
            httpsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
            httpsBinding.Security.Mode = BasicHttpsSecurityMode.Transport;

            var integerMaxValue = int.MaxValue;
            httpsBinding.MaxBufferSize = integerMaxValue;
            httpsBinding.MaxReceivedMessageSize = integerMaxValue;
            httpsBinding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            httpsBinding.AllowCookies = true;

            httpsBinding.ReceiveTimeout = timeout;
            httpsBinding.SendTimeout = timeout;
            httpsBinding.OpenTimeout = timeout;
            httpsBinding.CloseTimeout = timeout;

            return httpsBinding;
        }
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(string endpointUrl)
        {
            if (!endpointUrl.StartsWith("https://"))
            {
                throw new UriFormatException("The endpoint URL must start with https://.");
            }
            return new System.ServiceModel.EndpointAddress(endpointUrl);
        }
    }
}
