

CREATE PROCEDURE [dbo].[SP_SEL_MENU_FOR_USER]
    @USER_UID UNIQUEIDENTIFIER = null
AS
    -- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    SELECT M.ID
        ,M.DESCR
        ,M.URL
        ,ISNULL(M.PARENT_MENU_ID, 0) AS PARENT_MENU_ID
        ,M.LABEL_KEY
        ,M.ICON_CODE
    FROM MENU AS M
        INNER JOIN IMS_ROLE_MENU AS RM ON RM.IMS_ROLE_MENU_MENU_ID = M.ID
        INNER JOIN IMS_USER_RIGHTS AS RIGHTS ON RIGHTS.IMS_USER_RIGHTS_USER_ROLE_ID = IMS_ROLE_MENU_USER_ROLE_ID
    WHERE RIGHTS.IMS_USER_RIGHTS_USER_UID = @USER_UID;