CREATE VIEW [dbo].[HR_VI_BIODATA]
AS 
	
SELECT BIODATA.HR_BIODATA_ID AS PRIMARY_KEY, 
       BIODATA.HR_BIODATA_USER_UID,
       BIODATA.HR_BIODATA_PERSONAL_TITLE_LOOKUP_ID, 
       BIODATA.HR_BIODATA_SURNAME, 
       BIODATA.HR_BIODATA_MIDDLE_NAME, 
       BIODATA.HR_BIODATA_NAME, 
       BIODATA.HR_BIODATA_GENEDER_LOOKUP_ID, 
       L_GENDER.IMS_LOOKUP_VALUE AS LOOKUP_GENDER_VAL, 
       L_PER_TITLE.IMS_LOOKUP_VALUE AS LOOKUP_PERSONAL_TITLE_VAL, 
       BIODATA.HR_BIODATA_BIRTH_DATE, 
       BIODATA.HR_BIODATA_BIRTH_PLACE
FROM dbo.HR_BIODATA AS BIODATA
     LEFT JOIN IMS_LOOKUP AS L_GENDER ON BIODATA.HR_BIODATA_GENEDER_LOOKUP_ID = L_GENDER.IMS_LOOKUP_ID
     LEFT JOIN IMS_LOOKUP AS L_PER_TITLE ON BIODATA.HR_BIODATA_PERSONAL_TITLE_LOOKUP_ID = L_PER_TITLE.IMS_LOOKUP_ID;