

CREATE VIEW [dbo].[IMS_VI_NARRATIVE_BY_TYPE]
AS
    SELECT 
        SECTION.ID,
        SECTION.REFERENCE_ID,
        SECTION_TYPE.CODE,
        SECTION_TYPE.DESCR,
        SECTION_TITLE,
        SECTION_TEXT
    FROM IMS_NARRATIVE_SECTION as SECTION
        INNER JOIN IMS_NARRATIVE_SECTION_TYPE AS SECTION_TYPE ON SECTION_TYPE.ID = SECTION.NARRATIVE_SECTION_TYPE_ID