
CREATE VIEW dbo.VI_IMS_LOCATION_DESCRIPTIVE
AS
SELECT LOC.IMS_LOCATION_ID
    ,LOC.IMS_LOCATION_ADMIN_AREA_ID_1
    ,AREA1.IMS_ADMIN_AREA_NAME AS AREA_1_NAME
    ,LOC.IMS_LOCATION_ADMIN_AREA_ID_2
    ,AREA2.IMS_ADMIN_AREA_NAME AS AREA_2_NAME
    ,LOC.IMS_LOCATION_ADMIN_AREA_ID_3
    ,AREA3.IMS_ADMIN_AREA_NAME AS AREA_3_NAME
    ,LOC.IMS_LOCATION_ADDRESS
    ,LOC.IMS_LOCATION_HISTORIC_ADDRESS
    ,LOC.IMS_LOCATION_LAT
    ,LOC.IMS_LOCATION_LON
FROM IMS_LOCATION AS LOC
    INNER JOIN IMS_ADMIN_AREA AS AREA1 ON AREA1.IMS_ADMIN_AREA_ID = LOC.IMS_LOCATION_ADMIN_AREA_ID_1
    INNER JOIN IMS_ADMIN_AREA AS AREA2 ON AREA2.IMS_ADMIN_AREA_ID = LOC.IMS_LOCATION_ADMIN_AREA_ID_2
    INNER JOIN IMS_ADMIN_AREA AS AREA3 ON AREA3.IMS_ADMIN_AREA_ID = LOC.IMS_LOCATION_ADMIN_AREA_ID_3